repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
      - id: name-tests-test
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-toml
      - id: check-symlinks
      - id: end-of-file-fixer
      - id: sort-simple-yaml
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.9.4
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [python, pyi]
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
        types_or: [python, pyi]
  # NOTE: conflict with ruff formatter tools.
  # - repo: https://github.com/asottile/reorder-python-imports
  #   rev: v3.14.0
  #   hooks:
  #   - id: reorder-python-imports
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
      - id: add-trailing-comma
  # NOTE : not able to disbale features: remove quoted annotations, as jaxtyping use `Annotated` annotations.
  # -   repo: https://github.com/asottile/pyupgrade
  #     rev: v3.19.1
  #     hooks:
  #     -   id: pyupgrade
  # -   repo: https://github.com/pre-commit/mirrors-mypy
  #     rev: v1.14.1
  #     hooks:
  #     -   id: mypy

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier
        types_or: [json, yaml, markdown]
