defaults:
  - train: default
  - network/ego_denoiser: default
  - network/denoising: default
  - train/loss: default
  - _self_

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${train.experiment_name}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${train.experiment_name}
    subdir: ${hydra.job.num}
