defaults:
  - train: vanilla
  - inference: amass_vanilla
  - network/ego_denoiser: vanilla
  - network/denoising: absolute_traj
  - train/loss: default
  - _self_

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${train.experiment_name}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${train.experiment_name}
    subdir: ${hydra.job.num}
