defaults:
  - train: hybrik
  - inference: amass_hybrik_during_train
  - network/ego_denoiser: hybrik
  - network/denoising: absolute_aadecomp_traj
  - train/loss: default
  - _self_

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${train.experiment_name}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${train.experiment_name}
    subdir: ${hydra.job.num}
