_target_: egoallo.config.data.egoexo.defaults.EgoExoConfig

traj_root: ./datasets/egoexo-default/takes
dataset_path: ./datasets/egoexo-default

bodypose_anno_dir: ./data/egoexo-default-gt-output/annotation/manual

gt_ground_height_anno_dir: ./exp/egoexo-default-exp/egoexo/egoexo-default-gt-output/bodypose/canonical/time_12_22_18_09_59/logs/annotation/manual
