_target_: egoallo.config.data.egoexo.defaults.EgoExoConfig

traj_root:
  _target_: pathlib.Path
  _args_:
    - data/egoexo-default-mount/takes
dataset_path:
  _target_: pathlib.Path
  _args_:
    - data/egoexo-default-mount

bodypose_anno_dir: ./data/egoexo-default-gt-output/annotation/manual

gt_ground_height_anno_dir: ./exp/egoexo-default-exp/egoexo/egoexo-default-gt-output/bodypose/canonical/time_12_22_18_09_59/logs/annotation/manual
