_target_: egoallo.network.DenoisingConfig

denoising_mode: absolute
joint_cond_mode: absrel
include_hands: false

loss_weights:
  betas: 0.2
  body_rotmats: 1.0
  contacts: 0.1
  hand_rotmats: 0.0
  R_world_root: 2.0
  t_world_root: 2.0
  joints: 0.0
  foot_skating: 0.3
  velocity: 0.1
